/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50645
Source Host           : localhost:3306
Source Database       : loveapp_databases

Target Server Type    : MYSQL
Target Server Version : 50645
File Encoding         : 65001

Date: 2020-08-26 22:59:18
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for market
-- ----------------------------
DROP TABLE IF EXISTS `market`;
CREATE TABLE `market` (
  `susd` int(80) DEFAULT NULL,
  `lux` text,
  `via` text,
  `bam` text,
  `egp` text,
  `btcp` text,
  `ssp` text,
  `scc` text,
  `nio` text,
  `nzd` text,
  `bay` text,
  `xmr` text,
  `nix` text,
  `brl` text,
  `ipc` text,
  `glc` text,
  `mxn` text,
  `xmy` text,
  `ugx` text,
  `hnl` text,
  `zar` text,
  `btc2` text,
  `iost` text,
  `usdccny1` text,
  `iqd` text,
  `dgb` text,
  `rp` text,
  `cup` text,
  `twd` text,
  `bca` text,
  `bcd` text,
  `rsd` text,
  `eif` text,
  `bcc` text,
  `bch` text,
  `myr` text,
  `zcash` text,
  `bci` text,
  `pivx` text,
  `btc` text,
  `sc` text,
  `uyu` text,
  `btg` text,
  `eosc` text,
  `omr` text,
  `sek` text,
  `kes` text,
  `btm` text,
  `timestamp` int(80) DEFAULT NULL,
  `ppc` text,
  `zcl` text,
  `qar` text,
  `ars` text,
  `btx` text,
  `flo` text,
  `nlg` text,
  `irr` text,
  `thb` text,
  `uzs` text,
  `nebl` text,
  `ugas` text,
  `rdd` text,
  `bdt` text,
  `ont` text,
  `ugasbmtpr` text,
  `kwd` text,
  `clam` text,
  `rub` text,
  `isk` text,
  `nmc` text,
  `doge` text,
  `mkd` text,
  `dzd` text,
  `bvb` text,
  `pab` int(80) DEFAULT NULL,
  `sgd` text,
  `kgs` text,
  `ut` text,
  `ada` text,
  `chf` text,
  `hrk` text,
  `zen` text,
  `tusd` int(80) DEFAULT NULL,
  `pax` text,
  `xrc` text,
  `em` text,
  `rvn` text,
  `vnd` text,
  `mlm` text,
  `strat` text,
  `cann` text,
  `aud` text,
  `khr` text,
  `vitae` text,
  `idr` text,
  `xrp` text,
  `emc` text,
  `aed` text,
  `dkk` text,
  `ugasbmnrl` text,
  `ugasbmupc` text,
  `bgn` text,
  `mmk` text,
  `nok` text,
  `sys` text,
  `xsn` text,
  `lkr` text,
  `bitg` text,
  `czk` text,
  `colx` text,
  `gas` text,
  `bhd` text,
  `kzt` text,
  `wan` text,
  `mona` text,
  `grs` text,
  `roadcny1` text,
  `npr` text,
  `mnt` text,
  `gbp` text,
  `mnx` text,
  `byn` text,
  `uno` text,
  `huf` text,
  `emc2` text,
  `dmd` text,
  `hc` text,
  `ckb` text,
  `bvbcny1` text,
  `eos` text,
  `tmc` text,
  `axe` text,
  `nad` text,
  `road` text,
  `pen` text,
  `block` text,
  `nas` text,
  `nrg` text,
  `nav` text,
  `gtq` text,
  `clp` text,
  `xvg` text,
  `tnd` text,
  `ethcny3` text,
  `moon` text,
  `ethcny2` text,
  `ethcny1` int(80) DEFAULT NULL,
  `sls` text,
  `kmd` text,
  `dop` text,
  `xwc` text,
  `smart` text,
  `gel` text,
  `mad` text,
  `ftc` text,
  `azn` text,
  `uah` text,
  `blk` text,
  `grin` text,
  `vtc` text,
  `cnx` text,
  `cny` text,
  `mbc` text,
  `bmd` int(80) DEFAULT NULL,
  `php` text,
  `bchsv` text,
  `phr` text,
  `atom` text,
  `jmd` text,
  `beam` text,
  `cop` text,
  `onion` text,
  `usd` int(80) DEFAULT NULL,
  `gusd` text,
  `etc` text,
  `eth` text,
  `usdt` text,
  `neo` text,
  `nvc` text,
  `xzc` text,
  `all` text,
  `wgr` text,
  `ves` text,
  `usdc` text,
  `ils` text,
  `ghs` text,
  `mdl` text,
  `bob` text,
  `amd` text,
  `try` text,
  `trx` text,
  `lbp` text,
  `dash` text,
  `usdtcny1` text,
  `jod` text,
  `usdtcny2` text,
  `usdtcny3` text,
  `hkd` text,
  `game` text,
  `eur` text,
  `cad` text,
  `part` text,
  `mur` text,
  `lcc` text,
  `gin` text,
  `ron` text,
  `dcr` text,
  `ngn` text,
  `crc` text,
  `pkr` text,
  `ltc` text,
  `btccny3` text,
  `btccny1` text,
  `btccny2` text,
  `sar` text,
  `ttd` text,
  `crw` text,
  `inr` text,
  `krw` text,
  `jpy` text,
  `pln` text,
  `pi` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of market
-- ----------------------------

-- ----------------------------
-- Table structure for marketinfo
-- ----------------------------
DROP TABLE IF EXISTS `marketinfo`;
CREATE TABLE `marketinfo` (
  `msg` text,
  `code` int(80) DEFAULT NULL,
  `data` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of marketinfo
-- ----------------------------
